# Generated by Django 4.2 on 2024-05-27 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='title',
        ),
        migrations.AddField(
            model_name='upload',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='upload',
            name='regulation',
            field=models.CharField(default='R00', max_length=5),
        ),
        migrations.AddField(
            model_name='upload',
            name='subject',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='upload',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
