# Generated by Django 4.2 on 2024-05-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_upload_title_upload_date_upload_regulation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='username',
            field=models.CharField(default='kk', max_length=100),
        ),
        migrations.AlterField(
            model_name='upload',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
